jobs:
  - reduce_sectors:
      reduce:
        - {r: 4, s: 1}
      select_integrals:
        select_mandatory_list:
          - [MI, target]
      integral_ordering: 5
      run_initiate: true
      run_triangular: true
      run_back_substitution: true
  - kira2file:
      target:
        - [MI, target]
