integralfamilies:
  - name: MI
    loop_momenta: [l1]
    top_level_sectors: [15]
    propagators:
      - [l1,0]
      - [l1+p1,0]
      - [l1+p1+p2,0]
      - [l1+p1+p2+p3,0]
    cut_propagators: []
