kinematics:
  incoming_momenta: [p1,p2,p3,p4]
  outgoing_momenta: []
  momentum_conservation: [p4,-p1-p2-p3]
  kinematic_invariants:
  scalarproduct_rules:
    - [[p1,p1], 0]
    - [[p2,p2], 0]
    - [[p3,p3], 0]
    - [[p1+p2,p1+p2], 1]
    - [[p2+p3,p2+p3], -3]
    - [[p1+p3,p1+p3], 2]
