integralfamilies:
  - name: MI
    loop_momenta: [k1,k2]
    top_level_sectors: [7]
    propagators:
      - [k1,2]
      - [k2-p1,3]
      - [k1+k2,5]
      - [k2,0]
      - [k1+p1,0]
    cut_propagators: []
